name: build and scan container

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image-registry:
        required: false
        type: string
        default: ghcr.io
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  hadolint:
    permissions:
      contents: read
    name: Hadolint
    uses: ./github/workflows/build-container/hadolint.yml
    with:
      dockerfile: ${{ inputs.dockerfile }}
  docker:
    uses: ./github/workflows/build-container/docker.yml
    needs:
      - hadolint
    with:
      context: ${{ inputs.context }}
      dockerfile: ${{ inputs.dockerfile }}
      image-registry: ${{ inputs.image-registry }}
      image-name: ${{ inputs.image-name }}
      image-tag: ${{ inputs.image-tag }}
    perimssions:
      contents: read
      packages: write
  dockle:
    uses: ./github/workflows/build-container/dockle.yml
    needs:
      - docker
    with:
      image-registry: ${{ inputs.image-registry }}
      image-name: ${{ inputs.image-name }}
      image-digest: ${{ needs.docker.outputs.image-digest }}
  trivy:
    uses: ./github/workflows/build-container/trivy.yml
    needs:
      - docker
    with:
      image-registry: ${{ inputs.image-registry }}
      image-name: ${{ inputs.image-name }}
      image-digest: ${{ needs.docker.outputs.image-digest }}
    permissions:
      packages: write
    secrets:
      cosign-key: ${{ secrets.cosign-key }}

    