# Copyright © TUM AET 2025 - 2025
#
# Licensed under the MIT License
#
# Authors: Benedikt Hofmann, Patrick Stoeckle, and other contributors
#
# SPDX-FileCopyrightText: 2025 TUM AET
#
# SPDX-License-Identifier: MIT

checks:
  exclude:
    # spring boot needs access at least to tmp, so we disable this check
    - "no-read-only-root-fs"
