# Copyright © Siemens 2025 - 2025
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: Kristi Balla, Patrick Stöckle
#
# SPDX-FileCopyrightText: 2025 Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

# kics-scan ignore
services:
  greetings:
    container_name: greetings
    ports:
      - "8080:8080"
    build:
      context: demo
      dockerfile: Dockerfile
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/greet"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
