services:
  server:
    image: ghcr.io/aet-devops25/w09-solution/server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://database:5432/mensa
      - LLM_SERVICE_URL=http://llm:5000
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    security_opt: 
      - no-new-privileges=true
    # TODO add healthcheck

  database:
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecret}
      - POSTGRES_DB=${POSTGRES_DB:-mensa}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    security_opt: 
      - no-new-privileges=true
    # TODO add healthcheck

  client:
    image: ghcr.io/aet-devops25/w09-solution/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8080/api}
    depends_on:
      - server
    restart: unless-stopped
    security_opt: 
      - no-new-privileges=true
    # TODO add healthcheck

  llm:
    image: ghcr.io/aet-devops25/w09-solution/llm:latest
    build:
      context: ./llm
      dockerfile: Dockerfile
    environment:
      - CHAIR_API_KEY=${CHAIR_API_KEY:-your_api_key_here}
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
    security_opt: 
      - no-new-privileges=true
    # TODO add healthcheck

volumes:
  db_data:
  # TODO add internal networks
