services:
  server:
    image: ghcr.io/kristi-balla/devops-demo/server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://database:5432/mensa
      - LLM_SERVICE_URL=http://llm:5000
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      llm:
        condition: service_healthy
    security_opt: 
      - no-new-privileges=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mensanet

  database:
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecret}
      - POSTGRES_DB=${POSTGRES_DB:-mensa}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    security_opt: 
      - no-new-privileges=true
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mensanet

  client:
    image: ghcr.io/kristi-balla/devops-demo/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://127.0.0.1:8080/api}
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    security_opt: 
      - no-new-privileges=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mensanet

  llm:
    image: ghcr.io/kristi-balla/devops-demo/llm:latest
    build:
      context: ./llm
      dockerfile: Dockerfile
    environment:
      - CHAIR_API_KEY=${CHAIR_API_KEY:-your_api_key_here}
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
    security_opt: 
      - no-new-privileges=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mensanet

volumes:
  db_data:

networks:
  mensanet:
    driver: bridge
