# Copyright © TUM AET 2025 - 2025
#
# Licensed under the MIT License
#
# Authors: Benedikt Hofmann, Patrick Stoeckle, and other contributors
#
# SPDX-FileCopyrightText: 2025 TUM AET
#
# SPDX-License-Identifier: MIT

# kics-scan ignore
services:
  greetings:
    container_name: greetings
    ports:
      - "8080:8080"
    build:
      context: demo
      dockerfile: Dockerfile
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test:
        ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/greet"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  ui:
    container_name: ui
    ports:
      - "9090:80"
    build:
      context: ui
      dockerfile: Dockerfile
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
