# Copyright © Siemens 2025 - 2025
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: Kristi Balla, Patrick Stöckle
#
# SPDX-FileCopyrightText: 2025 Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

version: "0.2"
dictionaryDefinitions:
  - name: project-words
    path: "./cspell.project-words.txt"
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - .git
  - node_modules
  - dist
  - build
  - coverage
  - "*.lock"
  - "*.svg"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
