# Copyright © TUM AET 2025 - 2025
#
# Licensed under the MIT License
#
# Authors: Benedikt Hofmann, Patrick Stoeckle, and other contributors
#
# SPDX-FileCopyrightText: 2025 TUM AET
#
# SPDX-License-Identifier: MIT

version: "0.2"
dictionaryDefinitions:
  - name: project-words
    path: "./cspell.project-words.txt"
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - .git
  - node_modules
  - dist
  - build
  - coverage
  - "*.lock"
  - "*.svg"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
