# Copyright © Siemens none - none
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: 
#
# SPDX-FileCopyrightText: none Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

[NEW_SCRIPT]
firstLine = ''
endLine = "\n"
beforeEachLine = '# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '#.*$'
lastLineDetectionPattern = '#.*$'

[JINJA]
firstLine = ''
endLine = "\n"
beforeEachLine = '# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '#.*$'
lastLineDetectionPattern = '#.*$'

[MARKDOWN]
firstLine = '<!--'
endLine = "-->\n"
beforeEachLine = ''
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '\s*<!--.*$'
lastLineDetectionPattern = '\s*-->.*$'
