# Copyright © TUM AET 2025 - 2025
#
# Licensed under the MIT License
#
# Authors: Benedikt Hofmann, Patrick Stoeckle, and other contributors
#
# SPDX-FileCopyrightText: 2025 TUM AET
#
# SPDX-License-Identifier: MIT

[NEW_SCRIPT]
firstLine = ''
endLine = "\n"
beforeEachLine = '# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '#.*$'
lastLineDetectionPattern = '#.*$'

[JINJA]
firstLine = ''
endLine = "\n"
beforeEachLine = '# '
afterEachLine = ''
allowBlankLines = false
multipleLines = false
padLines = false
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '#.*$'
lastLineDetectionPattern = '#.*$'

[MARKDOWN]
firstLine = '<!--'
endLine = "-->\n"
beforeEachLine = ''
afterEachLine = ''
allowBlankLines = false
multipleLines = true
padLines = false
firstLineDetectionPattern = '\s*<!--.*$'
lastLineDetectionPattern = '\s*-->.*$'
