apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: server
          image: ghcr.io/kristi-balla/devops-demo/server:main
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DATABASE_URL
              value: jdbc:postgresql://database:5432/mensa
            - name: LLM_SERVICE_URL
              value: http://llm:5000
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
          resources:
            requests:
              cpu: 1
              memory: 100Mi
            limits:
              cpu: 2
              memory: 500Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: demo
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
