# Copyright © TUM AET 2025 - 2025
#
# Licensed under the MIT License
#
# Authors: Benedikt Hofmann, Patrick Stoeckle, and other contributors
#
# SPDX-FileCopyrightText: 2025 TUM AET
#
# SPDX-License-Identifier: MIT

name: build and scan container

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image-registry:
        required: false
        type: string
        default: ghcr.io
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      ignore-codes:
        required: false
        type: string
        default: ""
    secrets:
      cosign-key:
        required: true

jobs:
  hadolint:
    permissions:
      contents: read
    name: Hadolint
    uses: ./.github/workflows/hadolint.yml
    with:
      dockerfile: ${{ inputs.dockerfile }}
  docker:
    uses: ./.github/workflows/docker.yml
    needs:
      - hadolint
    with:
      context: ${{ inputs.context }}
      dockerfile: ${{ inputs.dockerfile }}
      image-registry: ${{ inputs.image-registry }}
      image-name: ${{ inputs.image-name }}
      image-tag: ${{ inputs.image-tag }}
    permissions:
      contents: read
      packages: write
  dockle:
    uses: ./.github/workflows/dockle.yml
    needs:
      - docker
    with:
      image-registry: ${{ inputs.image-registry }}
      image-name: ${{ inputs.image-name }}
      image-digest: ${{ needs.docker.outputs.image-digest }}
      ignore-codes: ${{ inputs.ignore-codes }}
  trivy:
    uses: ./.github/workflows/trivy.yml
    needs:
      - docker
    with:
      image-registry: ${{ inputs.image-registry }}
      image-name: ${{ inputs.image-name }}
      image-digest: ${{ needs.docker.outputs.image-digest }}
    permissions:
      packages: write
    secrets:
      cosign-key: ${{ secrets.cosign-key }}
