# Copyright © TUM AET 2025 - 2025
#
# Licensed under the MIT License
#
# Authors: Benedikt Hofmann, Patrick Stoeckle, and other contributors
#
# SPDX-FileCopyrightText: 2025 TUM AET
#
# SPDX-License-Identifier: MIT

name: devops demo CI parent workflow

on:
  push: { branches: [main] }
  pull_request:

jobs:
  hawkeye:
    permissions:
      contents: read
    name: hawkeye
    uses: ./.github/workflows/hawkeye.yml
  gitleaks:
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    name: gitleaks
    uses: ./.github/workflows/gitleaks.yml
  java_linting:
    permissions:
      contents: read
      pull-requests: write
    name: java
    uses: ./.github/workflows/java.yml
  terraform_linting:
    uses: ./.github/workflows/tflint.yml
  k8s_linting:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/kube-linter.yml
  sast_1:
    permissions:
      contents: read
    uses: ./.github/workflows/sem-grep.yml
  sast_2:
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    uses: ./.github/workflows/kics.yml
  spellcheck:
    uses: ./.github/workflows/spelling.yml
  npm-audit:
    uses: ./.github/workflows/npm-audit.yml
  build-java-container:
    uses: ./.github/workflows/build-container.yml
    with:
      context: ./demo
      dockerfile: ./demo/Dockerfile
      image-registry: ghcr.io
      image-name: kristi-balla/devops-demo/java
      image-tag: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
    permissions:
      contents: read
      packages: write
    secrets:
      cosign-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
  build-js-container:
    uses: ./.github/workflows/build-container.yml
    with:
      context: ./ui
      dockerfile: ./ui/Dockerfile
      image-registry: ghcr.io
      image-name: kristi-balla/devops-demo/ui
      image-tag: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
      ignore-codes: "CIS-DI-0010"
    permissions:
      contents: read
      packages: write
    secrets:
      cosign-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
