# Copyright © Siemens 2025 - 2025
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: Kristi Balla, Patrick Stöckle
#
# SPDX-FileCopyrightText: 2025 Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

name: devops demo CI parent workflow

on:
  push: { branches: [main] }
  pull_request:

jobs:
  hawkeye:
    permissions:
      contents: read
    name: hawkeye
    uses: ./.github/workflows/hawkeye.yml
  gitleaks:
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    name: gitleaks
    uses: ./.github/workflows/gitleaks.yml
  java_linting:
    permissions:
      contents: read
      pull-requests: write
    name: java
    uses: ./.github/workflows/java.yml
  dockerfile_linting:
    permissions:
      contents: read
      pull-requests: write
    name: dockerfile_linting
    uses: ./.github/workflows/hadolint.yml
  terraform_linting:
    uses: ./.github/workflows/tflint.yml
  k8s_linting:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/kube-linter.yml
  sast_1:
    permissions:
      contents: read
    uses: ./.github/workflows/sem-grep.yml
  sast_2:
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    uses: ./.github/workflows/kics.yml
  deploy:
    permissions:
      contents: read
      packages: write
    needs:
      - dockerfile_linting
      - java_linting
      - sast_1
      - sast_2
    uses: ./.github/workflows/docker.yml
  container_image_linting:
    needs: [deploy]
    uses: ./.github/workflows/dockle.yml
  spellcheck:
    uses: ./.github/workflows/spelling.yml
