# Copyright © Siemens 2025 - 2025
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: Kristi Balla, janmalix, renovate[bot]
#
# SPDX-FileCopyrightText: 2025 Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

name: devops demo CI parent workflow

on:
  push: { branches: [main] }
  pull_request:

jobs:
  hawkeye:
    permissions:
      contents: read
    name: hawkeye
    uses: ./.github/workflows/hawkeye.yml
  gitleaks:
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    name: gitleaks
    uses: ./.github/workflows/gitleaks.yml
  java_linting:
    permissions:
      contents: read
      pull-requests: write
    name: java
    uses: ./.github/workflows/java.yml
  terraform_linting:
    uses: ./.github/workflows/tflint.yml
  k8s_linting:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/kube-linter.yml
  sast_1:
    permissions:
      contents: read
    uses: ./.github/workflows/semgrep.yml
  sast_2:
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    uses: ./.github/workflows/kics.yml
  spellcheck:
    uses: ./.github/workflows/spelling.yml
  npm-audit:
    uses: ./.github/workflows/npm-audit.yml
  build-backend-container:
    uses: ./.github/workflows/build-container.yml
    with:
      context: ./demo
      dockerfile: ./demo/Dockerfile
      image-authors: "Patrick Stoeckle"
      image-description: "Sample backend based on Spring Boot"
      image-name: kristi-balla/devops-demo/backend
      image-registry: ghcr.io
      image-tag: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
      image-title: "DevOps Demo Backend"
    permissions:
      contents: read
      packages: write
    secrets:
      cosign-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
  build-frontend-container:
    uses: ./.github/workflows/build-container.yml
    with:
      context: ./ui
      dockerfile: ./ui/Dockerfile
      ignore-codes: "CIS-DI-0010"
      image-authors: "Benedikt Hofmann"
      image-description: "Sample Frontend based on Angular"
      image-name: kristi-balla/devops-demo/frontend
      image-registry: ghcr.io
      image-tag: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
      image-title: "DevOps Demo Frontend"
    permissions:
      contents: read
      packages: write
    secrets:
      cosign-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
