name: main

on:
  push: { branches: [main] }
  pull_request:

jobs:
  spellcheck:
    uses: ./.github/workflows/spelling.yml
  dockerfile_linting:
    permissions:
      contents: read
      pull-requests: write
    name: dockerfile_linting
    uses: ./.github/workflows/hadolint.yml
  k8s_linting:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/kube-linter.yml
  semgrep:
    permissions:
      contents: read
    uses: ./.github/workflows/sem-grep.yml
  terraform_linting:
    uses: ./.github/workflows/tflint.yml
  kics:
    permissions:
      security-events: write
      actions: read
      contents: read
      pull-requests: write
    uses: ./.github/workflows/kics.yml
  java:
    permissions:
      contents: read
      pull-requests: write
    name: java
    uses: ./.github/workflows/java.yml
  docker:
    permissions:
      contents: read
      packages: write
    needs:
      - dockerfile_linting
      - java
      - kics
    uses: ./.github/workflows/docker.yml
  dockle:
    needs: [docker]
    uses: ./.github/workflows/dockle.yml
