name: main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  spellcheck:
    uses: ./.github/workflows/spelling.yml
  dockerfile_linting:
    name: dockerfile_linting
    uses: ./.github/workflows/dockerfile-lint.yml
  k8s_linting:
    uses: ./.github/workflows/kube-linter.yml
  kics:
    uses: ./.github/workflows/kics.yml
  java:
    name: java
    uses: ./.github/workflows/java.yml
  docker:
    needs:
      - dockerfile_linting
      - java
    uses: ./.github/workflows/docker.yml