# Copyright © Siemens 2025 - 2025
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: Kristi Balla, Patrick Stöckle
#
# SPDX-FileCopyrightText: 2025 Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

name: container image linting

on:
  workflow_call:
    inputs:
      image-digest:
        description: The digest of the built image
        required: true
        type: string
      image-registry:
        description: The container registry to push the image to
        required: false
        type: string
        default: ghcr.io
      image-name:
        description: The name of the image to build and push
        required: true
        type: string
      ignore-codes:
        description: Comma-separated list of codes to ignore
        required: false
        type: string
        default: ""

jobs:
  image-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.image-registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Run Dockle
        uses: erzz/dockle-action@v1
        with:
          image: "${{ inputs.image-registry }}/${{ inputs.image-name }}@${{ inputs.image-digest }}"
          report-format: sarif
          report-name: dockle-results
          failure-threshold: fatal
          exit-code: 1
          dockle-version: 0.4.11
          accept-extensions: pem
          ignore-codes: ${{ inputs.ignore-codes }}
