name: hadolint

on:
  workflow_call:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfiles
        id: lint-dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "*Dockerfile"
          recursive: true
