name: hadolint

on:
  workflow_call:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfiles
        id: lint-dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "*Dockerfile"
          recursive: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.lint-dockerfiles.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;
      
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
