# Copyright © TUM AET 2025 - 2025
#
# Licensed under the MIT License
#
# Authors: Benedikt Hofmann, Patrick Stoeckle, and other contributors
#
# SPDX-FileCopyrightText: 2025 TUM AET
#
# SPDX-License-Identifier: MIT

name: container image linting

on:
  workflow_call:
    inputs:
      image-digest:
        description: The digest of the built image
        required: true
        type: string
      image-registry:
        description: The container registry to push the image to
        required: false
        type: string
        default: ghcr.io
      image-name:
        description: The name of the image to build and push
        required: true
        type: string
      ignore-codes:
        description: Comma-separated list of codes to ignore
        required: false
        type: string
        default: ""

jobs:
  image-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ inputs.image-registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Run Dockle
        uses: goodwithtech/dockle-action@e30e6af832aad6ea7dca2a248d31a85eab6dbd68
        with:
          image: "${{ inputs.image-registry }}/${{ inputs.image-name }}@${{ inputs.image-digest }}"
          exit-level: fatal
          exit-code: 1
          ignore: ${{ inputs.ignore-codes }}
