name: container image building

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kristi-balla/devops-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      # Can read the contents of the repository
      contents: read
      # Can write to the packages in the repository
      # This is needed to push the built image to the GitHub Container Registry
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # This is a small helper, because GitHub Actions don't allow this outside a run block.
        # Since the variable GITHUB_HEAD_REF isn't available on main, we have to set the default to that
      - name: Fetch branch name
        run: echo "IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_HEAD_REF:-main}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: demo
          file: demo/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
