# Copyright © Siemens 2025 - 2025
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: Kristi Balla, janmalix
#
# SPDX-FileCopyrightText: 2025 Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

on:
    workflow_call:

jobs:
    hawkeye:
        name: hawkeye
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

            - name: Run Hawkeye
              uses: korandoru/hawkeye@cdc68d9c8ace500aefcd8f4dd39b915cd06305dd
              with:
                github_token: ${{ github.token }}
