# Copyright © Siemens 2025 - 2025
#
# Licensed under the Siemens Inner Source License 1.5
#
# Authors: Kristi Balla, Patrick Stoeckle, janmalix, renovate[bot]
#
# SPDX-FileCopyrightText: 2025 Siemens
#
# SPDX-License-Identifier: LicenseRef-Siemens-ISL-1.5

name: spellcheck using cspell and typos

on:
  workflow_call:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Documentation Spell Check
        uses: streetsidesoftware/cspell-action@69543c3f9f14d4fcc6004c7bee03c4d366f11d64
        with:
          config: "./cspell.config.yml"

      - name: Code Spell Check
        uses: crate-ci/typos@b1ae8d918b6e85bd611117d3d9a3be4f903ee5e4
