name: spellcheck

on:
  workflow_call:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Documentation Spell Check
        uses: streetsidesoftware/cspell-action@v7
        with:
          config: './cspell.config.yml'

      - name: Code Spell Check
        uses: crate-ci/typos@v1.33.1
